"""add video analysis jobs

Revision ID: c1f05d99c019
Revises: c44fd29dedb6
Create Date: 2026-08-17 17:08:15.888437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f05d99c019'
down_revision: Union[str, Sequence[str], None] = 'c44fd29dedb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_analysis_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('result_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_video_analysis_jobs_analysis_type'), 'video_analysis_jobs', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_video_analysis_jobs_status'), 'video_analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_video_analysis_jobs_video_id'), 'video_analysis_jobs', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_analysis_jobs_video_id'), table_name='video_analysis_jobs')
    op.drop_index(op.f('ix_video_analysis_jobs_status'), table_name='video_analysis_jobs')
    op.drop_index(op.f('ix_video_analysis_jobs_analysis_type'), table_name='video_analysis_jobs')
    op.drop_table('video_analysis_jobs')
    # ### end Alembic commands ###
